In [10]:
import numpy as np

In [11]:
ml=[1,2,3]

In [12]:
ar=np.array(ml)

In [13]:
ar

array([1, 2, 3])

In [14]:
mt=[[1,2,3],[4,5,6],[7,8,9]]

In [15]:
np.array(mt)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [22]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [26]:
np.eye(4) #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.random.rand(4,3)

array([[0.13364461, 0.95621422, 0.06941595],
       [0.16758162, 0.48350618, 0.06165545],
       [0.9137869 , 0.00843871, 0.01304078],
       [0.47497482, 0.09377048, 0.75117309]])

In [30]:
np.random.randn(4,3) #normal distribution

array([[ 2.04071591, -1.40256819,  1.84170589],
       [-0.06557709, -0.87496152, -2.68211098],
       [ 0.38644955, -0.7224376 ,  0.26395137],
       [ 0.96596339, -0.44230138,  1.53575859]])

In [34]:
np.random.randint(1,100,10)#lower inclusive, upper exclusive

array([15, 48, 42, 21, 72, 93, 14, 95, 89, 32])

In [44]:
ar=np.random.randint(1,100,25)
ar

array([ 4, 46, 80, 46, 61, 32, 20, 73, 49, 22, 98, 72, 33, 31, 45, 41, 26,
       84, 90, 63, 96, 81, 62, 63, 26])

In [55]:
arr=ar.reshape(5,5) #total size can't change
arr

array([[ 4, 46, 80, 46, 61],
       [32, 20, 73, 49, 22],
       [98, 72, 33, 31, 45],
       [41, 26, 84, 90, 63],
       [96, 81, 62, 63, 26]])

In [58]:
arr.max()

98

In [59]:
arr.argmax()

10

In [60]:
arr.shape

(5, 5)

In [62]:
arr.dtype

dtype('int64')

In [63]:
from numpy.random import randint

In [64]:
randint(2,10)

6

In [66]:
ar[6]

20

In [72]:
arr[0:2,2:4]

array([[80, 46],
       [73, 49]])

In [74]:
ar1=np.arange(0,11)
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
ar1[1:3]=100
ar1

array([  0, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [95]:
sl_ar1=ar1[8:10]
sl_ar1[:]=99
ar1

array([  0, 100, 100,   3,   4,   5,   6,   7,  99,  99,  10])

In [100]:
ar1_cp=ar1.copy()
ar1_cp[:]=99
ar1

array([  0, 100, 100,   3,   4,   5,   6,   7,  99,  99,  10])

In [101]:
ar1_cp

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [112]:
ar2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
ar2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
ar2d[2][1]

8

In [113]:
ar2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [114]:
ar1=np.arange(0,11)
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
b_ar1=ar1<5
b_ar1

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False])

In [118]:
ar1[ar1<5]

array([0, 1, 2, 3, 4])

In [119]:
ar2_2d=np.arange(50).reshape(5,10)
ar2_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [120]:
ar2_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [121]:
ar1+ar1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [122]:
ar1-ar1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [123]:
ar1*ar1

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [126]:
ar1-56

array([-56, -55, -54, -53, -52, -51, -50, -49, -48, -47, -46])

In [127]:
ar1/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [128]:
ar1/0

<ipython-input-128-56626b90235a>:1: RuntimeWarning: divide by zero encountered in true_divide
  ar1/0
<ipython-input-128-56626b90235a>:1: RuntimeWarning: invalid value encountered in true_divide
  ar1/0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [129]:
0/ar1

<ipython-input-129-289387b706df>:1: RuntimeWarning: invalid value encountered in true_divide
  0/ar1


array([nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [130]:
np.sqrt(ar1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [131]:
np.exp(ar1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [132]:
np.sin(ar1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [133]:
np.log(ar1)

<ipython-input-133-59e1cd4f7632>:1: RuntimeWarning: divide by zero encountered in log
  np.log(ar1)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [134]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [135]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [138]:
np.ones(10)*5 #np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [139]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [140]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [141]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [142]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [150]:
np.random.rand(1)

array([0.08112452])

In [151]:
np.random.randn(25)

array([-1.3807238 , -1.1465518 ,  1.7265476 ,  0.63880911, -0.90443395,
        1.65275253,  0.13120217, -0.78873901,  1.81640536, -0.36945311,
       -0.45323554, -0.74008136, -0.85713675,  0.35388529,  2.09371232,
       -1.13940605,  0.5244201 , -0.10204258,  0.65040528,  0.17906472,
       -0.02993086, -0.40762508,  0.72058971, -0.01612548, -0.11514556])

In [158]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [163]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [164]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [166]:
mt=np.arange(1,26).reshape(5,5)
mt

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [168]:
mt[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [171]:
mt[3,4]

20

In [175]:
mt[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [176]:
mt[4,]

array([21, 22, 23, 24, 25])

In [177]:
mt[3:,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [179]:
mt.sum()

325

In [180]:
mt.std()

7.211102550927978

In [181]:
sum(mt)

array([55, 60, 65, 70, 75])